# Generated by Django 3.2 on 2022-06-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfeedback',
            name='like',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
